#define BUG_RECURSIVE_MACRO_EXPANSION 0
#define BUG_EXTERN_BLOCK_DEFINE 0
#define BUG_SELF_INCLUDING_MACRO_FUNCTION 0
#define BUG_ATTRIBUTE_KEYWORD 0
#define BUG_OPERATOR_PASTE 0
#define BUG_BODY_SCOPE_ACROSS_C_TOKEN_CURSOR_BOUNDARY 0

#define BUG_HAS_INCLUDE 0
#define BUG_HAS_INCLUDE_NEXT 0
